version: "3.7"

services:
  spark-master:
    image: kshp/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7070:7070"
      - "8080:8080"
  spark-worker-1:
    image: kshp/spark-worker:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8080"